title: Introduction to Quantitative Methods
logo: /assets/img/logo_new.jpeg
description: This is a course on quantitative methods. Created by Ozlem Tuncel (she/her/hers)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
